config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  concern :commentable do
    resources :comments, only: :create
  end

  resources :categories, concerns: [:commentable] do
    resources :posts, concerns: [:commentable], only: %i[new create update show destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint(8)        not null, primary key
#  name        :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ApplicationRecord
  include Commentable
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :name, format: { with: NAME_REGEX, message: MESSAGE_FORMAT_NAME }
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :bigint(8)        not null, primary key
#  content          :text             not null
#  commentable_type :string
#  commentable_id   :bigint(8)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  author           :string           not null
#

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

  validates :content, :author, presence: true
  validates :author, format: { with: AUTHOR_MANE_REGEX, message: MESSAGE_FORMAT_AUTHOR }
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, dependent: :delete_all, as: :commentable
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint(8)        not null, primary key
#  name        :string           not null
#  content     :text
#  category_id :bigint(8)        not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ApplicationRecord
  include Commentable
  belongs_to :category
  has_one_attached :file

  validates :name, presence: true
  validates :name, format: { with: NAME_REGEX, message: MESSAGE_FORMAT_NAME }
  validates :file, size: { less_than: 2.megabytes, message: 'must be less than 2 MB' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :category, only: %i[show new edit]

  def index
    @categories = Category.all
  end

  def show
    @post = category.posts.new
  end

  def new
  end

  def edit
  end

  def update
    if category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category successfully created.'
    else
      render :new
    end
  end

  def destroy
    category.destroy

    redirect_to categories_path, notice: 'Category successfully deleted.'
  end

  private

  def category
    @category ||= params[:id] ? Category.find(params[:id]) : Category.new
  end

  helper_method :category

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable, only: :create

  def create
    @comment = @commentable.comments.create(comment_params)
  end

  private

  def set_commentable
    @commentable = Category.find_by(id: params[:category_id]) || Post.find_by(id: params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :author)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :post, only: %i[show]

  def show
  end

  def create
    @post = category.posts.new(post_params)
    @post.save
  end

  def update
    post.update(post_params)

    @category = post.category
  end

  def destroy
    post.destroy
  end

  private

  def category
    @category ||= params[:category_id] ? Category.find(params[:category_id]) : post.category
  end

  def post
    @post ||= params[:id] ? Post.find(params[:id]) : category.posts.new
  end

  helper_method :post, :category

  def post_params
    params.require(:post).permit(:name, :content, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  NAME_REGEXP = /^[A-Z][a-z]+\s[a-z]{2}+[.]/

  def flash_class(key)
    case key
    when 'notice'
      'alert alert-info'
    when 'success'
      'alert alert-success'
    when 'warning', 'alert'
      'alert alert-warning'
    end
  end
end

app/views/categories/_category.html.slim
tr[id="category_#{category.id}"]
  td
    = link_to category.name, category_path(category)
  td
    => link_to "Edit", edit_category_path(category), class: 'btn btn-primary'
    = link_to "Delete", category_path(category), method: :delete, class: 'btn btn-primary'

app/views/categories/_form.html.slim
= form_with model: category, **form_params do |f|
  p
    = f.label :name
    = f.text_field :name, class: 'form-control', rows: 4
  p
    = f.label :description
    = f.text_area :description, class: 'form-control', rows: 8
  = f.submit 'Save'

app/views/categories/edit.html.slim
= render 'shared/errors', resource: category
= render partial: 'form', locals: { category: category, form_params: { local: true } }

app/views/categories/index.html.slim
.row
  .col-2
  .col-8
    h1
      = "List categories:"
    .float-right
      = link_to 'Add category', new_category_path, class: 'btn btn-primary'

    table.table
      thead.thead-light
        tr
          th
            = "Name"
          th
            = "Actions"
      = render @categories

app/views/categories/new.html.slim
= render 'shared/errors', resource: category
= render partial: 'form', locals: { category: category, form_params: { local: true } }

app/views/categories/show.html.slim
.category
  h1 = "Category:"
  p
    = "Name: #{category.name}"
  p
    = "Description: #{category.description}"

  .comment_errors
    = render 'shared/errors', resource: @comment

  .category-comments
    | Comments:
    = render category.comments
    = render 'comments/form', commentable: category

  = link_to 'Add comment', '#', class: 'button-category-comment', data: { category_id: category.id }

.post_errors
  = render 'shared/errors', resource: @post

.posts
  h1 = "Posts list:"
  = render category.posts

= form_with model: [category, @post], class: 'new-post' do |f|
  p
    = f.label :name
    = f.text_field :name, class: 'form-control'
  p
    = f.label :content
    = f.text_area :content, class: 'form-control'
    = f.label :file
    = f.file_field :file
  = f.submit 'Add post'

app/views/comments/_comment.html.slim
p= "Author: #{comment.author}"
p= "Comment: #{comment.content}"

app/views/comments/_form.html.slim
= form_with model: [commentable, commentable.comments.new], class: 'hidden',
            html: { id: "Add-#{commentable.class}-Comment-#{commentable.id}" } do |f|
  = f.label :author, 'Comment author'
  = f.text_field :author, class: 'form-control', rows: 8
  = f.label :content, 'Comment body'
  = f.text_area :content, class: 'form-control', rows: 8
  = f.submit 'Save comment'

app/views/comments/create.js.erb
<% if @comment.errors.present? %>
  $('.comment_errors').html('<%= render 'shared/errors', resource: @comment %>');
<% else %>
  $(".<%= @comment.commentable_type.downcase %>-comments").append('<%= j render @comment %>');
  $('textarea').val('');
  $("form#Add-<%= @comment.commentable_type %>-Comment-<%= @comment.commentable.id %>").addClass('hidden');
  $(".button-<%= @comment.commentable_type.downcase %>-comment").removeClass('hidden');
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title BLOG
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render 'shared/flash'

      = yield

app/views/posts/_post.html.slim
- if post.persisted?
  li[id="post_#{post.id}"]
    => link_to post.name, post_path(post)
    p
      - if post.file.attached?
        = image_tag post.file, size: "100x100"
    => link_to 'Delete post', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, remote: true
    = link_to 'Edit post', '#', class: 'edit-post-link', data: { post_id: post.id }

    = form_with model: post, class: 'hidden', html: { id: "edit-post-#{post.id}" } do |f|
      p
        = f.label :name
        = f.text_field :name, class: 'form-control'
      p
        = f.label :content
        = f.text_area :content, class: 'form-control'
        = f.label :file
        = f.file_field :file
      = f.submit 'Save post'

app/views/posts/create.js.erb
<% if post.errors.present? %>
  $('.post_errors').html('<%= render 'shared/errors', resource: post %>');
<% else %>
  $('.posts').append('<%= j render post %>');
  $('#post_name, #post_content').val('');
<% end %>

app/views/posts/destroy.js.erb
$('#post_'+ <%= post.id %>).remove();

app/views/posts/show.html.slim
.post
  h1 = "Post:"
  p
    = "Name: #{post.name}"
  p
    = "Content: #{post.content}"

  - if post.file.attached?
    = image_tag post.file, size: "300x300"

  .comment_errors
    = render 'shared/errors', resource: @comment

  .post-comments
    | Comments:
    = render post.comments
    = render 'comments/form', commentable: post

  = link_to 'Add comment', '#',class: 'button-post-comment', data: { post_id: post.id }

app/views/posts/update.js.erb
<% if post.errors.present? %>
$('.post_errors').html('<%= render 'shared/errors', resource: post %>');
<% else %>
$('#post_'+ <%= post.id %>).replaceWith('<%= j render post %>');
<% end %>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>" role="alert">
    <%= value.html_safe %>
  </div>
<% end %>